import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './index.html',
    './src/**/*.{ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#384763',
        'tertiary': '#232627',
        'secondary-fixed-dim': '#b7c7e9',
        'error': '#ba1a1a',
        'background': '#fcf9f8',
        'on-tertiary-fixed': '#191c1d',
        'tertiary-container': '#383b3c',
        'on-tertiary-container': '#a3a5a6',
        'on-secondary-container': '#505f7d',
        'primary-fixed': '#dae2ff',
        'outline': '#75777e',
        'on-tertiary-fixed-variant': '#454748',
        'on-primary-fixed-variant': '#3a4666',
        'surface-container-highest': '#e5e2e1',
        'surface': '#fcf9f8',
        'surface-variant': '#e5e2e1',
        'surface-container-high': '#eae7e7',
        'surface-container-lowest': '#ffffff',
        'outline-variant': '#c6c6ce',
        'on-tertiary': '#ffffff',
        'on-surface-variant': '#45464e',
        'secondary-fixed': '#d7e3ff',
        'on-primary-container': '#98a4c9',
        'inverse-primary': '#bac6ec',
        'tertiary-fixed-dim': '#c5c7c8',
        'surface-tint': '#525e7f',
        'inverse-surface': '#313030',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#bac6ec',
        'on-secondary-fixed': '#0b1b35',
        'surface-bright': '#fcf9f8',
        'on-surface': '#1c1b1b',
        'primary': '#182442',
        'inverse-on-surface': '#f3f0ef',
        'primary-container': '#2e3a59',
        'on-error-container': '#93000a',
        'surface-container': '#f0eded',
        'on-primary-fixed': '#0d1a38',
        'surface-dim': '#dcd9d9',
        'tertiary-fixed': '#e1e3e4',
        'secondary-container': '#cbdafd',
        'surface-container-low': '#f6f3f2',
        'on-secondary': '#ffffff',
        'secondary': '#505f7c',
        'on-background': '#1c1b1b',
        'on-primary': '#ffffff',
        'error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xl: '32px',
        xs: '4px',
        'margin-mobile': '16px',
        md: '16px',
        unit: '4px',
        lg: '24px',
        gutter: '16px',
        'margin-desktop': '40px',
        sm: '8px',
      },
      fontFamily: {
        'display-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}

export default config
